# Profile section
profile:
  first_name: Giovanni Gamaliel
  last_name: López Padilla
  picture: static/img/image.jpg
  contact:
    address_one: Torreón, Coahuila
    address_two:
    phone: 871-278-37-70
  email: giovannilopez9808@gmail.com
  description: Soy un científico entusiasmado en el análisis de datos y su representación física. Practicante de Data Science con el desarrollo de soluciones tecnológicas haciendo uso de algoritmos, teorías físicas, programación, modelos matemáticos, extracción y visualización de datos. Apoyando a organizaciones civiles con herramientas computacionales.

# Social section
social:
  website:
  wpforms: https://github.com/giovannilopez9808/Resume/raw/main/Document/cv_gglp.pdf
  github: https://github.com/giovannilopez9808
  twitter:
  linkedin: https://www.linkedin.com/in/gamaliel-lópez-padilla
  facebook:
  dev:
  medium:

# Education section
education:
  item4:
    institution: Centro de Investigación en Matemáticas
    program: Maestría en Ciencias con Especialidad en Computación y Matemáticas Industriales
    from: Agosto 2021
    to: Julio 2023
  item3:
    institution: MUFRAMEX 2nd Thematic School on Deep Generative Models
    program: Escuela de otoño donde se abordaron modelos generativos
    from: 16 Noviembre 2022
    to: 19 Noviembre 2022
  item2:
    institution: Universidad Autónoma de Nuevo León
    program: Licenciatura en física
    from: Agosto 2016
    to: Diciembre 2020
  item1:
    institution: Universidad Nacional de Córdoba
    program: Ecuaciones en Derivadas Parciales, desde la teoría a las aproximaciones numéricas
    from: Agosto 2020
    to: Diciembre 2020
  item0:
    institution: Qiskit Global Summer School
    program: Escuela de verano impartida por IBM para el uso de Qiskit para la simulación de la computación cuántica
    from: Julio 2020
    to: Julio 2020

# Community section:
community:
  item4:
    institution: Centro de Investigación en Matemáticas
    program: Ayudante de catedra de la clase de Temas Selectos de Aprendizaje Maquina I
    description: Realice actividades de apoyo durante la clase. Las actividades fueron apyo teórico a los estudiantes de manera personal y general, revisión y calificación de las tareas semanales.
    from: 15 enero 2023
    to: 21 mayo 2023
  item3:
    institution: Centro de Investigación en Matemáticas
    program: Ayudante de MUFRAMEX school
    description: Fungi como ayudante durante las sesiones de practica durante la escuela de otoño MUFRAMEX. Brinde apoyo teórico y practico en las implementaciones de los modelos generativos.
    from: 16 Noviembre 2022
    to: 19 Noviembre 2022
  item2:
    institution: QuantumHispano
    program: Cofundador
    description: Cofundador de la comunidad QuantumHispano, la cual es la encargada de la coordinación de cursos para la introducción en la computación cuántica y la divulgación de los avances científicos en esta rama de la física y computación
    from: Agosto 2019
    to: Agosto 2021
  item1:
    institution: Universidad Autónoma de Nuevo León
    program: Talleres Estudiantiles FCFM-UANL
    description: Impartí y coordine un conjunto de talleres dirigido hacia los estudiantes de la Facultad con el proposito de que el estudiante tuviera un óptimo desarrollo. Los talleres fueron enfocados en la enseñanza de herramientas avanzadas para el análisis y visualización de datos obtenidas a partir de simulaciones.
    from: Agosto 2018
    to: Julio 2020
  item0:
    institution: Facultad de Ciencias Físico-Matemáticas
    program: Coordinación de la Asociación de Estudiantes de Física
    description: Desarrolle la coordinación de Tesorería de la Asociación de Estudiantes de Física. Se crearon actividades económicas para la recaudación de fondos con el proposito de brindar apoyos económicos hacia comunidad estudiantil.
    from: Agosto 2017
    to: Noviembre 2018

# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - git-alt
  - github
  - slack
  - markdown
  - linux
extra_skills:
  - Extracción de datos de la NASA, ESA, AERONET, DAVIS
  - Automatización de de análisis de datos
  - Ajuste de modelos matemáticos basado en datos experimentales
  - Procesamiento de imagenes
  - Análisis de datos gubernamentales e institucionales
  - Modelos basados en aprendizaje maquina, deep learning y generativos

# Projects section
projects:
  item8:
    title: Ultraviolet Radiation Environment of a Tropical Megacity in Transition Mexico City 2000–2019
    link: https://pubs.acs.org/doi/10.1021/acs.est.0c08515
    github:
    img: trend_paper.jpg
  item11:
    title: Instalación sugerida para los sensores Skye UVA, UVB y UVI
    link: https://github.com/giovannilopez9808/Documents/raw/master/Informes/Informe_radsolar_29Mar21.pdf
    github:
    img: informe_sima.png
  item10:
    title: TES para tu salud
    link: http://tes-v1.herokuapp.com/
    github:
    img: tes_webpage.png
  item9:
    title: Comparación de tres métodos usando radiación solar para la producción de Pre-Vitamina D3 en la piel.
    link: https://github.com/giovannilopez9808/Documents/raw/master/Articulos/Vitamin_D_2020.pdf
    github:
    img: vitamin_paper.png
  item7:
    title: Análisis basado en imágenes satelitales de Google Earth
    link: https://github.com/giovannilopez9808/Documents/raw/master/Informes/Edge_detection_2020.pdf
    github:
    img: animation.gif
  item6:
    title: Localización de incendios en el Delta del río Paraná
    link: https://github.com/giovannilopez9808/Documents/raw/master/Informes/Focos%20de%20incendio%20en%20las%20islas%20del%20Paran%C3%A1%20%20frente%20a%20Rosario%20%20(Piacentini%2C%20Ipi%C3%B1a%2C%20Lopez-Padilla%2C%20Bolmaro)%20(Piacentini).pdf
    github:
    img: viirs-Fire.gif
  item5:
    title: Creación de fractales usando el conjunto de Julia
    github:
    link: https://github.com/giovannilopez9808/Julia_WorkShop_2021Q1/blob/main/soluci%C3%B3n_primer_proyecto_1/Primer_proyecto.ipynb
    img: fractal.gif
  item4:
    title: Estimación de los TES en la Ciudad de México
    description: Por medio de la definición de la dosis UVA y eritemica y el uso de datos de irradiancia proporcionados por la SEDEMA se obtuvieron los tiempos de exposicion solar por minuto en el horario 8:00 hrs - 18:00 hrs.
    link: https://github.com/giovannilopez9808/Documents/raw/master/Posters/2020/CNF/TES/main.pdf
    github:
    img: tes_poster.png
  item3:
    title: Análisis de parámetros atmosféricos en el AMM
    link: https://github.com/giovannilopez9808/Documents/raw/master/Posters/2020/CNF/PM10/main.pdf
    github:
    img: pm_poster.png
  item2:
    title: Estudio de la irradiancia solar con dos modelos de transferencia radiativa y su comparación con mediciones
    link: https://github.com/giovannilopez9808/Documents/raw/master/Posters/2019/CNF/Transferencia%20radiativa/main.pdf
    github:
    img: transferencia_poster.png
  item1:
    title: Análisis de las irradiancias UVA y eritémica medidas por el SEDEMA
    link: https://github.com/giovannilopez9808/Documents/raw/master/Posters/2019/AFA/Analisis%20indice%20UV/Analisis%20de%20irradiancia.pdf
    github:
    img: irradiancia_poster.png
